/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatorioExemploRouteImport } from './routes/relatorio-exemplo'
import { Route as IndexRouteImport } from './routes/index'

const RelatorioExemploRoute = RelatorioExemploRouteImport.update({
  id: '/relatorio-exemplo',
  path: '/relatorio-exemplo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/relatorio-exemplo': typeof RelatorioExemploRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/relatorio-exemplo': typeof RelatorioExemploRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/relatorio-exemplo': typeof RelatorioExemploRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/relatorio-exemplo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/relatorio-exemplo'
  id: '__root__' | '/' | '/relatorio-exemplo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RelatorioExemploRoute: typeof RelatorioExemploRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorio-exemplo': {
      id: '/relatorio-exemplo'
      path: '/relatorio-exemplo'
      fullPath: '/relatorio-exemplo'
      preLoaderRoute: typeof RelatorioExemploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RelatorioExemploRoute: RelatorioExemploRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
